/**
 * One-off migration: add tags to existing course data.
 * Run: npx tsx scripts/add-tags.ts
 */
import { readFileSync, writeFileSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"
import type { YogaCourse } from "../src/data/types"
import { generateTags } from "../src/data/tags"

const __dirname = dirname(fileURLToPath(import.meta.url))
const outPath = join(__dirname, "../src/data/index.ts")

const content = readFileSync(outPath, "utf-8")
const match = content.match(/export const courses: YogaCourse\[] = (\[[\s\S]*\])/)
if (!match) {
  console.error("Could not parse courses from index.ts")
  process.exit(1)
}

const courses: YogaCourse[] = JSON.parse(match[1])

for (const course of courses) {
  course.tags = generateTags(course)
}

const output = `// This file is auto-generated by scripts/scrape.ts — do not edit manually
import type { YogaCourse } from "./types"

export const courses: YogaCourse[] = ${JSON.stringify(courses, null, 2)}
`

writeFileSync(outPath, output, "utf-8")
console.log(`Updated ${courses.length} courses with tags`)
