import { writeFileSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))
import { websites } from "../src/data/websites-data"
import type { WebsiteEntry, DropInClass } from "../src/data/types"
import { generateDropInTags } from "../src/data/tags"
import { anthropic, parseMaxAgeDays, loadExistingData, getUrlsToSkip, getPageText, requireApiKey } from "./scrape-utils"

const outPath = join(__dirname, "../src/data/drop-in.ts")
const maxAgeDays = parseMaxAgeDays()

function loadExisting(): DropInClass[] {
  return loadExistingData<DropInClass>(outPath, /export const dropInClasses: DropInClass\[] = (\[[\s\S]*\])/)
}

async function extractDropInClasses(
  pageText: string,
  entry: WebsiteEntry
): Promise<DropInClass[]> {
  console.log(`  Extracting drop-in classes with Claude API...`)

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 4096,
    system: `You extract structured data about drop-in yoga classes from website text.
Drop-in classes are regular weekly classes that students can attend without enrolling in a full course.
Return ONLY a JSON array of class objects. If no drop-in classes are found, return an empty array [].
Each class object must match this schema exactly:
{
  "schoolName": "string - name of the yoga school",
  "className": "string - name of the class, e.g. 'Morning Hatha Yoga'",
  "url": "string - will be provided, use as-is",
  "style": "string - yoga style, e.g. Hatha, Vinyasa, Ashtanga, Yin, Kundalini, Meditation, Pranayama",
  "schedule": [
    {
      "dayOfWeek": "number - 0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday",
      "startTime": "string - 24h format HH:MM, e.g. '07:00'",
      "endTime": "string or null - 24h format HH:MM if available, e.g. '08:30'"
    }
  ],
  "price": { "amount": "number", "currency": "string" } or null if not available,
  "description": "string - brief description (1-2 sentences)"
}
If a class runs every day, include all 7 days in the schedule array.
If a class runs on specific days, only include those days.
Return raw JSON only. No markdown, no code fences, no explanation.`,
    messages: [
      {
        role: "user",
        content: `Extract drop-in yoga class information from this website text. The school is "${entry.schoolName}" and the URL is "${entry.url}".\n\nWebsite text:\n${pageText}`,
      },
    ],
  })

  let text =
    response.content[0].type === "text" ? response.content[0].text : ""
  text = text.replace(/^```(?:json)?\s*\n?/i, "").replace(/\n?```\s*$/i, "").trim()

  try {
    const classes = JSON.parse(text) as Omit<DropInClass, "updatedAt" | "tags" | "location">[]
    const now = new Date().toISOString()
    const withMeta: DropInClass[] = classes.map((c) => ({
      ...c,
      price: c.price ?? undefined,
      schedule: c.schedule.map((s) => ({
        dayOfWeek: s.dayOfWeek,
        startTime: s.startTime,
        ...(s.endTime ? { endTime: s.endTime } : {}),
      })),
      tags: generateDropInTags(c),
      location: entry.location,
      updatedAt: now,
    }))
    console.log(`  Found ${withMeta.length} drop-in class(es)`)
    return withMeta
  } catch {
    console.warn(`  ⚠ Failed to parse Claude response as JSON`)
    console.warn(`  Response preview: ${text.slice(0, 200)}`)
    return []
  }
}

function writeOutput(classes: DropInClass[]) {
  const output = `// This file is auto-generated by scripts/scrape-drop-in.ts — do not edit manually
import type { DropInClass } from "./types"

export const dropInClasses: DropInClass[] = ${JSON.stringify(classes, null, 2)}
`
  writeFileSync(outPath, output, "utf-8")
  console.log(`\nWrote ${classes.length} drop-in classes to src/data/drop-in.ts`)
}

async function main() {
  requireApiKey()

  const existing = loadExisting()
  const freshUrls = getUrlsToSkip(existing, maxAgeDays)
  const toScrape = websites.filter((w) => w.pageType === "drop-in").filter((w) => !freshUrls.has(w.url))

  if (toScrape.length === 0) {
    console.log("All drop-in websites are up to date. Use --update-older-than-days 0 to re-scrape all.")
    return
  }

  console.log(`Scraping ${toScrape.length} drop-in websites...\n`)
  const newDropIns: DropInClass[] = []

  for (const entry of toScrape) {
    const text = await getPageText(entry)
    if (!text) continue
    try {
      const classes = await extractDropInClasses(text, entry)
      newDropIns.push(...classes)
    } catch (error) {
      console.warn(`  ⚠ Claude API error for ${entry.url}: ${error}`)
    }
  }

  const scrapedUrls = new Set(toScrape.map((w) => w.url))
  const kept = existing.filter((c) => !scrapedUrls.has(c.url))
  writeOutput([...kept, ...newDropIns])
}

main()
