import { writeFileSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))
import { websites } from "../src/data/websites-data"
import type { WebsiteEntry, YogaCourse } from "../src/data/types"
import { generateTags } from "../src/data/tags"
import { anthropic, parseMaxAgeDays, loadExistingData, getUrlsToSkip, getPageText, requireApiKey } from "./scrape-utils"

const outPath = join(__dirname, "../src/data/training.ts")
const maxAgeDays = parseMaxAgeDays()

function loadExisting(): YogaCourse[] {
  return loadExistingData<YogaCourse>(outPath, /export const courses: YogaCourse\[] = (\[[\s\S]*\])/)
}

async function extractCourses(
  pageText: string,
  entry: WebsiteEntry
): Promise<YogaCourse[]> {
  console.log(`  Extracting courses with Claude API...`)

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 4096,
    system: `You extract structured data about yoga courses from website text.
Return ONLY a JSON array of course objects. If no yoga courses are found, return an empty array [].
Each course object must match this schema exactly:
{
  "schoolName": "string - name of the yoga school",
  "courseName": "string - name of the specific course",
  "url": "string - will be provided, use as-is",
  "type": "string - e.g. Yin Yoga Teacher Training, Hatha Yoga TTC, 200-Hour Yoga TTC, Ashtanga Vinyasa TTC, Yoga Retreat, Kundalini Yoga TTC, Aerial Yoga TTC",
  "certificationLevel": "string - e.g. 50hr, 100hr, 200hr RYT, 300hr, 500hr, or empty string if not specified",
  "durationDays": "number - duration in days, 0 if unknown",
  "price": { "amount": "number", "currency": "string - e.g. USD, EUR, INR" },
  "description": "string - brief description of the course (2-3 sentences)",
  "upcomingDates": ["string - ISO date format YYYY-MM-DD for each upcoming start date"],
  "accommodation": "boolean or string - true/false, or description like 'Private room included'",
  "meals": "boolean or string - true/false, or description like '3 vegetarian meals daily'",
  "rating": "number or null - rating out of 5 if available",
  "reviewCount": "number or null - number of reviews if available"
}
Return raw JSON only. No markdown, no code fences, no explanation.`,
    messages: [
      {
        role: "user",
        content: `Extract yoga course information from this website text. The school is "${entry.schoolName}" and the URL is "${entry.url}".\n\nWebsite text:\n${pageText}`,
      },
    ],
  })

  let text =
    response.content[0].type === "text" ? response.content[0].text : ""
  text = text.replace(/^```(?:json)?\s*\n?/i, "").replace(/\n?```\s*$/i, "").trim()

  try {
    const courses = JSON.parse(text) as Omit<YogaCourse, "updatedAt">[]
    const now = new Date().toISOString()
    const withTimestamp: YogaCourse[] = courses.map((c) => ({ ...c, tags: generateTags(c), location: entry.location, updatedAt: now }))
    console.log(`  Found ${withTimestamp.length} course(s)`)
    return withTimestamp
  } catch {
    console.warn(`  ⚠ Failed to parse Claude response as JSON`)
    console.warn(`  Response preview: ${text.slice(0, 200)}`)
    return []
  }
}

function writeOutput(courses: YogaCourse[]) {
  const output = `// This file is auto-generated by scripts/scrape-trainings.ts — do not edit manually
import type { YogaCourse } from "./types"

export const courses: YogaCourse[] = ${JSON.stringify(courses, null, 2)}
`
  writeFileSync(outPath, output, "utf-8")
  console.log(`\nWrote ${courses.length} courses to src/data/training.ts`)
}

async function main() {
  requireApiKey()

  const existing = loadExisting()
  const freshUrls = getUrlsToSkip(existing, maxAgeDays)
  const toScrape = websites.filter((w) => w.pageType === "training").filter((w) => !freshUrls.has(w.url))

  if (toScrape.length === 0) {
    console.log("All training websites are up to date. Use --update-older-than-days 0 to re-scrape all.")
    return
  }

  console.log(`Scraping ${toScrape.length} training websites...\n`)
  const newCourses: YogaCourse[] = []

  for (const entry of toScrape) {
    const text = await getPageText(entry)
    if (!text) continue
    try {
      const courses = await extractCourses(text, entry)
      newCourses.push(...courses)
    } catch (error) {
      console.warn(`  ⚠ Claude API error for ${entry.url}: ${error}`)
    }
  }

  const scrapedUrls = new Set(toScrape.map((w) => w.url))
  const kept = existing.filter((c) => !scrapedUrls.has(c.url))
  writeOutput([...kept, ...newCourses])
}

main()
