import * as cheerio from "cheerio"
import Anthropic from "@anthropic-ai/sdk"
import { writeFileSync } from "fs"
import { join } from "path"
import { websites } from "../src/data/websites-data"
import type { WebsiteEntry, YogaCourse } from "../src/data/types"

const anthropic = new Anthropic()

async function fetchPageText(entry: WebsiteEntry): Promise<string | null> {
  try {
    console.log(`Fetching: ${entry.url}`)
    const response = await fetch(entry.url, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      },
    })
    if (!response.ok) {
      console.warn(`  ⚠ HTTP ${response.status} for ${entry.url}`)
      return null
    }
    const html = await response.text()
    const $ = cheerio.load(html)

    // Remove non-content elements
    $("script, style, nav, footer, header, iframe, noscript").remove()

    // Extract text from body
    const text = $("body").text().replace(/\s+/g, " ").trim()

    // Limit to ~8000 chars to stay within reasonable token limits
    return text.slice(0, 8000)
  } catch (error) {
    console.warn(`  ⚠ Failed to fetch ${entry.url}: ${error}`)
    return null
  }
}

async function extractCourses(
  pageText: string,
  entry: WebsiteEntry
): Promise<YogaCourse[]> {
  console.log(`  Extracting courses with Claude API...`)

  const response = await anthropic.messages.create({
    model: "claude-opus-4-6",
    max_tokens: 4096,
    system: `You extract structured data about yin yoga courses from website text.
Return ONLY a JSON array of course objects. If no yin yoga courses are found, return an empty array [].
Each course object must match this schema exactly:
{
  "schoolName": "string - name of the yoga school",
  "courseName": "string - name of the specific course",
  "url": "string - will be provided, use as-is",
  "type": "string - e.g. Yin Yoga Teacher Training, Yin Yoga Retreat, Yin & Yang TTC",
  "certificationLevel": "string - e.g. 50hr, 100hr, 200hr RYT, or empty string if not specified",
  "durationDays": "number - duration in days, 0 if unknown",
  "price": { "amount": "number", "currency": "string - e.g. USD, EUR, INR" },
  "description": "string - brief description of the course (2-3 sentences)",
  "upcomingDates": ["string - ISO date format YYYY-MM-DD for each upcoming start date"],
  "accommodation": "boolean or string - true/false, or description like 'Private room included'",
  "meals": "boolean or string - true/false, or description like '3 vegetarian meals daily'",
  "rating": "number or null - rating out of 5 if available",
  "reviewCount": "number or null - number of reviews if available"
}
Return raw JSON only. No markdown, no code fences, no explanation.`,
    messages: [
      {
        role: "user",
        content: `Extract yin yoga course information from this website text. The school is "${entry.schoolName}" and the URL is "${entry.url}".\n\nWebsite text:\n${pageText}`,
      },
    ],
  })

  const text =
    response.content[0].type === "text" ? response.content[0].text : ""

  try {
    const courses: YogaCourse[] = JSON.parse(text)
    console.log(`  Found ${courses.length} course(s)`)
    return courses
  } catch {
    console.warn(`  ⚠ Failed to parse Claude response as JSON`)
    return []
  }
}

function writeOutput(courses: YogaCourse[]) {
  const output = `// This file is auto-generated by scripts/scrape.ts — do not edit manually
import type { YogaCourse } from "./types"

export const courses: YogaCourse[] = ${JSON.stringify(courses, null, 2)}
`

  const outPath = join(import.meta.dirname, "../src/data/index.ts")
  writeFileSync(outPath, output, "utf-8")
  console.log(`\nWrote ${courses.length} courses to src/data/index.ts`)
}

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("Error: ANTHROPIC_API_KEY environment variable is required")
    process.exit(1)
  }

  console.log(`Scraping ${websites.length} websites...\n`)

  const allCourses: YogaCourse[] = []

  for (const entry of websites) {
    const text = await fetchPageText(entry)
    if (!text) continue

    const courses = await extractCourses(text, entry)
    allCourses.push(...courses)
  }

  writeOutput(allCourses)
}

main()
