// This file is auto-generated by scripts/scrape.ts — do not edit manually
import type { DropInClass } from "./types"

export const dropInClasses: DropInClass[] = [
  {
    "schoolName": "Arogya Yoga School",
    "className": "Morning Drop-in Hatha, Ashtanga & Vinyasa Yoga",
    "url": "https://www.arogyayogaschool.com/drop-in-yoga-class-in-rishikesh.php",
    "style": "Hatha, Ashtanga, Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "07:00",
        "endTime": "09:00"
      }
    ],
    "price": {
      "amount": 5,
      "currency": "USD"
    },
    "description": "A daily morning drop-in class focusing on Hatha, Ashtanga, and Vinyasa asanas, Pranayama, and guided meditation, beginning with mantra chanting. No registration required; Sunday is off.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      },
      {
        "label": "Vinyasa",
        "category": "style"
      },
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:23:48.025Z"
  },
  {
    "schoolName": "Arogya Yoga School",
    "className": "Evening Drop-in Hatha, Ashtanga & Vinyasa Yoga",
    "url": "https://www.arogyayogaschool.com/drop-in-yoga-class-in-rishikesh.php",
    "style": "Hatha, Ashtanga, Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "16:30",
        "endTime": "18:30"
      }
    ],
    "price": {
      "amount": 5,
      "currency": "USD"
    },
    "description": "A daily evening drop-in class focusing on Hatha, Ashtanga, and Vinyasa asanas, Pranayama, and guided meditation, beginning with mantra chanting. No registration required; Sunday is off.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      },
      {
        "label": "Vinyasa",
        "category": "style"
      },
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:23:48.025Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Morning Ashtanga Yoga",
    "url": "https://worldpeaceyogaschool.com/drop-in-class.php",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 1,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 2,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 3,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 4,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 5,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 6,
        "startTime": "09:15",
        "endTime": "10:15"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "A daily drop-in Ashtanga Yoga class open to all levels. No advance booking needed; arrive 5 minutes before class starts.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:23:58.081Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Evening Hatha Yoga",
    "url": "https://worldpeaceyogaschool.com/drop-in-class.php",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "17:30",
        "endTime": "18:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "A daily drop-in Hatha Yoga class open to all levels. No advance booking needed; arrive 5 minutes before class starts.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:23:58.081Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Evening Ashtanga Yoga",
    "url": "https://worldpeaceyogaschool.com/drop-in-class.php",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 1,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 2,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 3,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 4,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 5,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 6,
        "startTime": "18:45",
        "endTime": "19:45"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "A daily drop-in evening Ashtanga Yoga class open to all levels. No advance booking needed; arrive 5 minutes before class starts.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:23:58.081Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Vinyasa Flow",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 2,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 3,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 4,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 5,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 6,
        "startTime": "07:00",
        "endTime": "08:10"
      }
    ],
    "description": "A dynamic Vinyasa Flow class held Monday through Saturday. Open to all levels with no prior experience required.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:11.335Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Breath Activation & Yoga Nidra",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Pranayama",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 2,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 3,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 4,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 5,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 6,
        "startTime": "08:15",
        "endTime": "09:15"
      }
    ],
    "description": "A combined breathwork activation and Yoga Nidra session held Monday through Saturday. Open to all levels.",
    "tags": [
      {
        "label": "Yoga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:11.335Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Kundalini Yoga with Maa Haripriya",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Kundalini",
    "schedule": [
      {
        "dayOfWeek": 6,
        "startTime": "10:00",
        "endTime": "11:15"
      },
      {
        "dayOfWeek": 0,
        "startTime": "10:00",
        "endTime": "11:15"
      }
    ],
    "description": "Kundalini Yoga class led by Maa Haripriya on Saturdays and Sundays. Open to all levels.",
    "tags": [
      {
        "label": "Kundalini",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:11.335Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Yin Yoga",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Yin",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "11:30",
        "endTime": "13:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "11:30",
        "endTime": "13:00"
      }
    ],
    "description": "A restorative Yin Yoga class held on Mondays and Fridays. Open to all levels.",
    "tags": [
      {
        "label": "Yin",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:11.335Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Ashtanga Vinyasa",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "16:30",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:30",
        "endTime": "17:30"
      }
    ],
    "description": "Ashtanga Vinyasa class held on Mondays and Tuesdays. Open to all levels.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:11.335Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Hatha Yoga",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 3,
        "startTime": "16:30",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:30",
        "endTime": "17:30"
      }
    ],
    "description": "A traditional Hatha Yoga class held on Wednesdays and Fridays. Open to all levels.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:11.335Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Classical Hatha Yoga (Summer)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 0,
        "startTime": "08:00",
        "endTime": "09:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Traditional Classical Hatha Yoga class available daily during summer season (2nd March to 30th October). Walk-in registration, suitable for all levels.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:41.095Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Beginner Yoga Class (Summer)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 0,
        "startTime": "10:00",
        "endTime": "11:00"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Beginner-friendly yoga class offered daily during summer season (2nd March to 30th October). Walk-in registration with no long-term commitment required.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:41.095Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Hatha Flow Vinyasa (Summer)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 0,
        "startTime": "16:00",
        "endTime": "17:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Hatha Flow Vinyasa class offered daily during summer season (2nd March to 30th October). Walk-in registration suitable for all levels.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:41.095Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Ashtanga Vinyasa Yoga (Summer)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 0,
        "startTime": "17:30",
        "endTime": "19:00"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Ashtanga Vinyasa Yoga class offered daily during summer season (2nd March to 30th October). Walk-in registration for all levels.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:41.095Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Classical Hatha Yoga (Winter)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 0,
        "startTime": "09:00",
        "endTime": "10:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Traditional Classical Hatha Yoga class available daily during winter season (1st November to 28th February). Walk-in registration, suitable for all levels.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:41.095Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Beginner Yoga Class (Winter)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 0,
        "startTime": "11:00",
        "endTime": "12:00"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Beginner-friendly yoga class offered daily during winter season (1st November to 28th February). Walk-in registration with no long-term commitment required.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:41.095Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Hatha Flow Vinyasa (Winter)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 0,
        "startTime": "16:00",
        "endTime": "17:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Hatha Flow Vinyasa class offered daily during winter season (1st November to 28th February). Walk-in registration suitable for all levels.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:41.095Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Ashtanga Vinyasa Yoga (Winter)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 0,
        "startTime": "17:30",
        "endTime": "19:00"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Ashtanga Vinyasa Yoga class offered daily during winter season (1st November to 28th February). Walk-in registration for all levels.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:41.095Z"
  },
  {
    "schoolName": "Vinyasa Yoga Academy",
    "className": "Drop-in Ashtanga Yoga",
    "url": "https://vinyasayogaacademy.com/",
    "style": "Ashtanga",
    "schedule": [],
    "description": "Drop-in Ashtanga yoga sessions offered at Vinyasa Yoga Academy in Rishikesh, India. Classes follow traditional Ashtanga Vinyasa yoga techniques.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:47.490Z"
  },
  {
    "schoolName": "Vinyasa Yoga Academy",
    "className": "Drop-in Hatha Yoga",
    "url": "https://vinyasayogaacademy.com/",
    "style": "Hatha",
    "schedule": [],
    "description": "Drop-in Hatha yoga sessions offered at Vinyasa Yoga Academy in Rishikesh, India. Classes draw on traditional Hatha yoga techniques rooted in the Himalayan tradition.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:47.490Z"
  },
  {
    "schoolName": "Vinyasa Yoga Academy",
    "className": "Drop-in Vinyasa Yoga",
    "url": "https://vinyasayogaacademy.com/",
    "style": "Vinyasa",
    "schedule": [],
    "description": "Drop-in Vinyasa yoga sessions offered at Vinyasa Yoga Academy in Rishikesh, India. Classes blend traditional and modern Vinyasa yoga practices.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:24:47.490Z"
  },
  {
    "schoolName": "Aranya Yoga",
    "className": "Drop In Ashtanga Yoga",
    "url": "https://www.aranyayogaashram.com/drop-in-yoga-class/",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "00:00"
      }
    ],
    "price": {
      "amount": 600,
      "currency": "INR"
    },
    "description": "Drop-in Ashtanga yoga class held at Aranya Yoga upper studio in Upper Bhagsu, Dharamshala. All levels are welcome and mats and tools are provided.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:24:57.038Z"
  },
  {
    "schoolName": "Aranya Yoga",
    "className": "Drop In Hatha Yoga",
    "url": "https://www.aranyayogaashram.com/drop-in-yoga-class/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "00:00"
      }
    ],
    "price": {
      "amount": 600,
      "currency": "INR"
    },
    "description": "Drop-in Hatha yoga class held at Aranya Yoga upper studio in Upper Bhagsu, Dharamshala. All levels are welcome and mats and tools are provided.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:24:57.038Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Morning Hatha Yoga Drop-In Class",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "07:30",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "07:30",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "07:30",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "07:30",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "07:30",
        "endTime": "09:00"
      }
    ],
    "price": {
      "amount": 350,
      "currency": "INR"
    },
    "description": "A 90-minute morning Hatha Yoga drop-in class focusing on classic postures with alignment and musculoskeletal awareness. Suitable for all levels from beginners to advanced practitioners.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:12.680Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Evening Hatha Yoga Drop-In Class",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "16:15",
        "endTime": "17:45"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:15",
        "endTime": "17:45"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:15",
        "endTime": "17:45"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:15",
        "endTime": "17:45"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:15",
        "endTime": "17:45"
      }
    ],
    "price": {
      "amount": 350,
      "currency": "INR"
    },
    "description": "A 90-minute evening Hatha Yoga drop-in class focusing on classic postures with alignment and musculoskeletal awareness. Suitable for all levels from beginners to advanced practitioners.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:12.680Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Morning Meditation & Pranayama Drop-In Class",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Meditation",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "10:00",
        "endTime": "11:00"
      }
    ],
    "price": {
      "amount": 350,
      "currency": "INR"
    },
    "description": "A drop-in meditation and pranayama class covering various active and passive meditative techniques including Vedic wisdom, mantra chanting, and OSHO active meditation. Taught by Meditation Guru Sarvottam ji.",
    "tags": [
      {
        "label": "Meditation",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:12.680Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Afternoon Meditation & Pranayama Drop-In Class",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Meditation",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "15:00",
        "endTime": "16:00"
      }
    ],
    "price": {
      "amount": 350,
      "currency": "INR"
    },
    "description": "A drop-in meditation and pranayama class covering various active and passive meditative techniques including Vedic wisdom, mantra chanting, and OSHO active meditation. Taught by Meditation Guru Sarvottam ji.",
    "tags": [
      {
        "label": "Meditation",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:12.680Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Sunday Yoga Asana & Meditation Workshop",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "08:00",
        "endTime": "11:30"
      }
    ],
    "price": {
      "amount": 800,
      "currency": "INR"
    },
    "description": "A 3.5-hour Sunday workshop combining 90 minutes of Hatha Yoga asana practice followed by a break and 90 minutes of meditation and pranayama techniques. Covers advanced postures, backbends, forward bends, and various meditation styles.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:12.680Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Hatha Yoga (All Levels)",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "09:00",
        "endTime": "10:30"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily Hatha Yoga class open to all levels, combining asanas, pranayama, and meditation to build strength, flexibility, and mental clarity.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:28.809Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Aerial Yoga",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Aerial",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "11:00",
        "endTime": "12:00"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily Aerial Yoga class offered at Shiva Yoga Center, open to drop-in students of all levels.",
    "tags": [
      {
        "label": "Aerial",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:28.809Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Acro Yoga (Beginner & Advanced)",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Acro Yoga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "14:00",
        "endTime": "15:00"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily Acro Yoga class suitable for both beginners and advanced practitioners at Shiva Yoga Center.",
    "tags": [
      {
        "label": "Multi-Style TTC",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:28.809Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Ashtanga Vinyasa Yoga",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "16:00",
        "endTime": "17:30"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily Ashtanga Vinyasa Yoga class combining dynamic movement and breathwork to build strength and flexibility.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:28.809Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Meditation",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Meditation",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "18:00",
        "endTime": "19:00"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily evening meditation class designed to cultivate inner peace, awareness, and mental clarity for all levels.",
    "tags": [
      {
        "label": "Meditation",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:25:28.809Z"
  }
]
