// This file is auto-generated by scripts/scrape-drop-in.ts — do not edit manually
import type { DropInClass } from "./types"

export const dropInClasses: DropInClass[] = [
  {
    "schoolName": "Arogya Yoga School",
    "className": "Morning Drop-in Hatha, Ashtanga & Vinyasa Yoga",
    "url": "https://www.arogyayogaschool.com/drop-in-yoga-class-in-rishikesh.php",
    "style": "Hatha, Ashtanga, Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "07:00",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "07:00",
        "endTime": "09:00"
      }
    ],
    "price": {
      "amount": 5,
      "currency": "USD"
    },
    "description": "Daily morning drop-in class focusing on Hatha, Ashtanga, and Vinyasa asanas, Pranayama, and guided meditation. Classes begin with mantra chanting and include individual attention on posture, alignment, and breathing. Sunday is off.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      },
      {
        "label": "Vinyasa",
        "category": "style"
      },
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:28.353Z"
  },
  {
    "schoolName": "Arogya Yoga School",
    "className": "Evening Drop-in Hatha, Ashtanga & Vinyasa Yoga",
    "url": "https://www.arogyayogaschool.com/drop-in-yoga-class-in-rishikesh.php",
    "style": "Hatha, Ashtanga, Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "16:30",
        "endTime": "18:30"
      }
    ],
    "price": {
      "amount": 5,
      "currency": "USD"
    },
    "description": "Daily evening drop-in class focusing on Hatha, Ashtanga, and Vinyasa asanas, Pranayama, and guided meditation. No registration required; students simply arrive at the school near Tapovan, Rishikesh. Sunday is off.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      },
      {
        "label": "Vinyasa",
        "category": "style"
      },
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:28.353Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Morning Ashtanga Yoga",
    "url": "https://worldpeaceyogaschool.com/drop-in-class.php",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 1,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 2,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 3,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 4,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 5,
        "startTime": "09:15",
        "endTime": "10:15"
      },
      {
        "dayOfWeek": 6,
        "startTime": "09:15",
        "endTime": "10:15"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "A daily drop-in Ashtanga Yoga class open to all levels. No advance booking needed; students are requested to arrive 5 minutes before class starts.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:39.533Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Evening Hatha Yoga",
    "url": "https://worldpeaceyogaschool.com/drop-in-class.php",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "17:30",
        "endTime": "18:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "17:30",
        "endTime": "18:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "A daily drop-in Hatha Yoga class held in the evening, open to all levels. No advance booking needed; students are requested to arrive 5 minutes before class starts.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:39.533Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Evening Ashtanga Yoga",
    "url": "https://worldpeaceyogaschool.com/drop-in-class.php",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 1,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 2,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 3,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 4,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 5,
        "startTime": "18:45",
        "endTime": "19:45"
      },
      {
        "dayOfWeek": 6,
        "startTime": "18:45",
        "endTime": "19:45"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "A daily drop-in Ashtanga Yoga class held in the late evening, open to all levels. No advance booking needed; students are requested to arrive 5 minutes before class starts.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:39.533Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Vinyasa Flow",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 2,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 3,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 4,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 5,
        "startTime": "07:00",
        "endTime": "08:10"
      },
      {
        "dayOfWeek": 6,
        "startTime": "07:00",
        "endTime": "08:10"
      }
    ],
    "description": "A dynamic Vinyasa Flow class held Monday through Saturday. Open to all levels with no prior experience required.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:57.228Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Breath Activation & Yoga Nidra",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Pranayama",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 2,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 3,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 4,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 5,
        "startTime": "08:15",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 6,
        "startTime": "08:15",
        "endTime": "09:15"
      }
    ],
    "description": "A breath activation and Yoga Nidra session held Monday through Saturday. Combines pranayama techniques with deep relaxation practices.",
    "tags": [
      {
        "label": "Breathwork",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:57.228Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Kundalini Yoga with Maa Haripriya",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Kundalini",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "10:00",
        "endTime": "11:15"
      },
      {
        "dayOfWeek": 6,
        "startTime": "10:00",
        "endTime": "11:15"
      }
    ],
    "description": "Kundalini Yoga class led by Maa Haripriya on Saturdays and Sundays. Open to all levels.",
    "tags": [
      {
        "label": "Kundalini",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:57.228Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Sound Healing Therapy",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Meditation",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "10:00",
        "endTime": "11:15"
      },
      {
        "dayOfWeek": 5,
        "startTime": "10:00",
        "endTime": "11:15"
      }
    ],
    "description": "Sound Healing Therapy sessions offered on Mondays and Fridays. A therapeutic practice using sound for relaxation and healing.",
    "tags": [
      {
        "label": "Meditation",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:57.228Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Yin Yoga",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Yin",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "11:30",
        "endTime": "13:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "11:30",
        "endTime": "13:00"
      }
    ],
    "description": "Yin Yoga class held on Mondays and Fridays. A slow-paced style targeting deep connective tissues for flexibility and relaxation.",
    "tags": [
      {
        "label": "Yin",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:57.228Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Ashtanga Vinyasa",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "16:30",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:30",
        "endTime": "17:30"
      }
    ],
    "description": "Ashtanga Vinyasa class held on Mondays and Tuesdays. A structured and dynamic yoga practice linking breath with movement.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:57.228Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Hatha Yoga",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 3,
        "startTime": "16:30",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:30",
        "endTime": "17:30"
      }
    ],
    "description": "Hatha Yoga class offered on Wednesdays and Fridays. A classical yoga practice focusing on postures and breath for balance and strength.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:57.228Z"
  },
  {
    "schoolName": "World Peace Yoga School",
    "className": "Acro Yoga",
    "url": "https://worldpeaceyogaschool.com/wellness/daily-drop-in-yoga-classes.php",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 6,
        "startTime": "16:30",
        "endTime": "17:30"
      }
    ],
    "description": "Acro Yoga class held on Saturdays combining yoga and acrobatics. A fun and engaging partner-based practice.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:51:57.228Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Classical Hatha Yoga (Summer)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "08:00",
        "endTime": "09:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "08:00",
        "endTime": "09:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Traditional Classical Hatha Yoga drop-in class available daily during summer season (2nd March to 30th October). Walk-in registration accepted.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:27.366Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Beginner Yoga Class (Summer)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "10:00",
        "endTime": "11:00"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Beginner-friendly yoga drop-in class offered daily during summer season (2nd March to 30th October). Suitable for those new to yoga with modifications provided.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:27.366Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Hatha Flow Vinyasa (Summer)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "16:00",
        "endTime": "17:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Hatha Flow Vinyasa drop-in class available daily during summer season (2nd March to 30th October). A dynamic blend of Hatha and Vinyasa yoga styles.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:27.366Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Ashtanga Vinyasa Yoga (Summer)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "17:30",
        "endTime": "19:00"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Ashtanga Vinyasa Yoga drop-in class offered daily during summer season (2nd March to 30th October). Focuses on a structured sequence of postures with breath control.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:27.366Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Classical Hatha Yoga (Winter)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "09:00",
        "endTime": "10:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Traditional Classical Hatha Yoga drop-in class available daily during winter season (1st November to 28th February). Walk-in registration accepted.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:27.366Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Beginner Yoga Class (Winter)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "11:00",
        "endTime": "12:00"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Beginner-friendly yoga drop-in class offered daily during winter season (1st November to 28th February). Suitable for those new to yoga with modifications provided.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:27.366Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Hatha Flow Vinyasa (Winter)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "16:00",
        "endTime": "17:30"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Hatha Flow Vinyasa drop-in class available daily during winter season (1st November to 28th February). A dynamic blend of Hatha and Vinyasa yoga styles.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:27.366Z"
  },
  {
    "schoolName": "Om Shanti Om Yoga Ashram",
    "className": "Ashtanga Vinyasa Yoga (Winter)",
    "url": "https://www.omshantiomyoga.com/drop-in-yoga-class-in-rishikesh.html",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "17:30",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "17:30",
        "endTime": "19:00"
      }
    ],
    "price": {
      "amount": 400,
      "currency": "INR"
    },
    "description": "Ashtanga Vinyasa Yoga drop-in class offered daily during winter season (1st November to 28th February). Focuses on a structured sequence of postures with breath control.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:27.366Z"
  },
  {
    "schoolName": "Vinyasa Yoga Academy",
    "className": "Drop-in Ashtanga Yoga",
    "url": "https://vinyasayogaacademy.com/",
    "style": "Ashtanga",
    "schedule": [],
    "description": "Drop-in Ashtanga yoga session offered at Vinyasa Yoga Academy in Rishikesh, India. Classes are available for students seeking traditional yoga practice without enrolling in a full teacher training course.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:34.803Z"
  },
  {
    "schoolName": "Vinyasa Yoga Academy",
    "className": "Drop-in Hatha Yoga",
    "url": "https://vinyasayogaacademy.com/",
    "style": "Hatha",
    "schedule": [],
    "description": "Drop-in Hatha yoga session offered at Vinyasa Yoga Academy in Rishikesh, India. Classes are available for students seeking traditional yoga practice without enrolling in a full teacher training course.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:34.803Z"
  },
  {
    "schoolName": "Vinyasa Yoga Academy",
    "className": "Drop-in Vinyasa Yoga",
    "url": "https://vinyasayogaacademy.com/",
    "style": "Vinyasa",
    "schedule": [],
    "description": "Drop-in Vinyasa yoga session offered at Vinyasa Yoga Academy in Rishikesh, India. Classes are available for students seeking traditional yoga practice without enrolling in a full teacher training course.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:34.803Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Hatha Yoga with Aman",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "08:00",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 3,
        "startTime": "08:00",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 4,
        "startTime": "08:00",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 6,
        "startTime": "08:00",
        "endTime": "09:15"
      },
      {
        "dayOfWeek": 0,
        "startTime": "08:00",
        "endTime": "09:15"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A Hatha Yoga class led by Aman. Drop-in sessions available as part of the Kaizen class timetable.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Backbend with Onam",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "09:30",
        "endTime": "10:45"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A backbend-focused yoga class led by Onam. Drop-in sessions available as part of the Kaizen class timetable.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Handstand & Strength with Karan",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 2,
        "startTime": "09:30",
        "endTime": "10:45"
      },
      {
        "dayOfWeek": 6,
        "startTime": "09:30",
        "endTime": "10:45"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A handstand and strength-focused yoga class led by Karan. Drop-in sessions available as part of the Kaizen class timetable.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Splits with Onam",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 3,
        "startTime": "09:30",
        "endTime": "10:45"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A splits-focused flexibility yoga class led by Onam. Drop-in sessions available as part of the Kaizen class timetable.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Inversions with Onam",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 5,
        "startTime": "09:30",
        "endTime": "10:45"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "An inversions-focused yoga class led by Onam. Drop-in sessions available as part of the Kaizen class timetable.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Free Community Mobility & Flexibility Class with Karan",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 3,
        "startTime": "10:45",
        "endTime": "11:45"
      }
    ],
    "price": {
      "amount": 0,
      "currency": "INR"
    },
    "description": "A free community mobility and flexibility class led by Karan. Open to all drop-in attendees.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Spinal Satisfaction & Backend Flow with Deepak Sir",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "16:30",
        "endTime": "17:45"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A spinal satisfaction and backend flow yoga class led by Deepak Sir. Drop-in sessions available as part of the Kaizen class timetable.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Restorative Yoga with Aayushi",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Yin",
    "schedule": [
      {
        "dayOfWeek": 2,
        "startTime": "16:30",
        "endTime": "17:45"
      },
      {
        "dayOfWeek": 6,
        "startTime": "16:30",
        "endTime": "17:45"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A restorative yoga class led by Aayushi. Drop-in sessions available as part of the Kaizen class timetable.",
    "tags": [
      {
        "label": "Yin",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Butter Hips Flow with Deepak Sir",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 3,
        "startTime": "16:30",
        "endTime": "17:45"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A hip-focused flow yoga class led by Deepak Sir. Drop-in sessions available as part of the Kaizen class timetable.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Kaizen Studio",
    "className": "Full Body Flow with Deepak Sir",
    "url": "https://kaizenstudio.fit/recovery",
    "style": "Vinyasa",
    "schedule": [
      {
        "dayOfWeek": 5,
        "startTime": "16:30",
        "endTime": "17:45"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A full body flow yoga class led by Deepak Sir. Drop-in sessions available as part of the Kaizen class timetable.",
    "tags": [
      {
        "label": "Vinyasa",
        "category": "style"
      }
    ],
    "location": "Rishikesh",
    "updatedAt": "2026-04-03T08:52:51.861Z"
  },
  {
    "schoolName": "Aranya Yoga",
    "className": "Drop in Ashtanga Yoga",
    "url": "https://www.aranyayogaashram.com/drop-in-yoga-class/",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "00:00"
      }
    ],
    "price": {
      "amount": 600,
      "currency": "INR"
    },
    "description": "Drop-in Ashtanga yoga class at Aranya Yoga's upper studio in Upper Bhagsu, Dharamshala. All levels are welcome and mats and tools are provided; contact via WhatsApp for exact timings.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:01.165Z"
  },
  {
    "schoolName": "Aranya Yoga",
    "className": "Drop in Hatha Yoga",
    "url": "https://www.aranyayogaashram.com/drop-in-yoga-class/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "00:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "00:00"
      }
    ],
    "price": {
      "amount": 600,
      "currency": "INR"
    },
    "description": "Drop-in Hatha yoga class at Aranya Yoga's upper studio in Upper Bhagsu, Dharamshala. All levels are welcome and mats and tools are provided; contact via WhatsApp for exact timings.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:01.165Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Morning Hatha Yoga Drop-In Class",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "07:30",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "07:30",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "07:30",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "07:30",
        "endTime": "09:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "07:30",
        "endTime": "09:00"
      }
    ],
    "price": {
      "amount": 350,
      "currency": "INR"
    },
    "description": "A 90-minute Hatha Yoga drop-in class focusing on classic Hatha yoga postures with emphasis on alignment and musculoskeletal awareness. Suitable for all levels from beginners to advanced practitioners.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:16.854Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Evening Hatha Yoga Drop-In Class",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 1,
        "startTime": "16:15",
        "endTime": "17:45"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:15",
        "endTime": "17:45"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:15",
        "endTime": "17:45"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:15",
        "endTime": "17:45"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:15",
        "endTime": "17:45"
      }
    ],
    "price": {
      "amount": 350,
      "currency": "INR"
    },
    "description": "A 90-minute evening Hatha Yoga drop-in class focusing on classic postures, alignment, and musculoskeletal awareness. Open to all levels of practitioners.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:16.854Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Morning Meditation & Pranayama Drop-In Class",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Meditation",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "10:00",
        "endTime": "11:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "10:00",
        "endTime": "11:00"
      }
    ],
    "price": {
      "amount": 350,
      "currency": "INR"
    },
    "description": "A drop-in Meditation and Pranayama class covering various active and passive meditative techniques including Japa Ajapa mantra chanting, OSHO active meditation, and Vedic meditation techniques. Taught by Meditation Guru Sarvottam ji.",
    "tags": [
      {
        "label": "Meditation",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:16.854Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Afternoon Meditation & Pranayama Drop-In Class",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Meditation",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "15:00",
        "endTime": "16:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "15:00",
        "endTime": "16:00"
      }
    ],
    "price": {
      "amount": 350,
      "currency": "INR"
    },
    "description": "An afternoon drop-in Meditation and Pranayama class covering various active and passive meditative techniques including Japa Ajapa mantra chanting, OSHO active meditation, and Vedic meditation techniques. Taught by Meditation Guru Sarvottam ji.",
    "tags": [
      {
        "label": "Meditation",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:16.854Z"
  },
  {
    "schoolName": "Mantra Yoga & Meditation",
    "className": "Sunday Yoga Asana & Meditation Workshop",
    "url": "https://mantrayogameditation.org/drop-in-yoga-classes-dharamsala/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "08:00",
        "endTime": "11:30"
      }
    ],
    "price": {
      "amount": 800,
      "currency": "INR"
    },
    "description": "A weekly Sunday workshop combining 90 minutes of Hatha Yoga asana practice followed by a short break and 90 minutes of Meditation and Pranayama techniques including Nada Yoga, Self Inquiry, Mantra Meditation, and Yoga Nidra.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:16.854Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Hatha Yoga (All Levels)",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Hatha",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "09:00",
        "endTime": "10:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "09:00",
        "endTime": "10:30"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily Hatha Yoga class open to all levels, focusing on physical postures to open the body's energy channels and bring harmony to both physical and energetic bodies.",
    "tags": [
      {
        "label": "Hatha",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:33.996Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Aerial Yoga",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Aerial",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "11:00",
        "endTime": "12:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "11:00",
        "endTime": "12:00"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily Aerial Yoga drop-in class held at Shiva Yoga Center, open to all levels seeking a unique and dynamic yoga experience.",
    "tags": [
      {
        "label": "Aerial",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:33.996Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Acro Yoga (Beginner & Advanced)",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Acro Yoga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "14:00",
        "endTime": "15:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "14:00",
        "endTime": "15:00"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily Acro Yoga drop-in class suitable for both beginners and advanced practitioners at Shiva Yoga Center.",
    "tags": [
      {
        "label": "Acroyoga",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:33.996Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Ashtanga Vinyasa Yoga",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Ashtanga",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 1,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 2,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 3,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 4,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 5,
        "startTime": "16:00",
        "endTime": "17:30"
      },
      {
        "dayOfWeek": 6,
        "startTime": "16:00",
        "endTime": "17:30"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily Ashtanga Vinyasa Yoga drop-in class designed to build strength, flexibility, and mental clarity through a dynamic flowing practice.",
    "tags": [
      {
        "label": "Ashtanga",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:33.996Z"
  },
  {
    "schoolName": "Shiva Darshan Yoga",
    "className": "Meditation",
    "url": "https://shivadarshanyoga.com/yoga-programs-retreats-dharamsala/classes/",
    "style": "Meditation",
    "schedule": [
      {
        "dayOfWeek": 0,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 1,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 2,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 3,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 4,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 5,
        "startTime": "18:00",
        "endTime": "19:00"
      },
      {
        "dayOfWeek": 6,
        "startTime": "18:00",
        "endTime": "19:00"
      }
    ],
    "price": {
      "amount": 500,
      "currency": "INR"
    },
    "description": "A daily drop-in meditation class aimed at guiding participants toward greater awareness, balance, and inner peace through stillness or movement-based practices.",
    "tags": [
      {
        "label": "Meditation",
        "category": "style"
      }
    ],
    "location": "Dharamshala",
    "updatedAt": "2026-04-03T08:53:33.996Z"
  }
]
