// This file is auto-generated by scripts/scrape.ts — do not edit manually
import type { YogaCourse } from "./types"

export const courses: YogaCourse[] = [
  {
    "schoolName": "Yin Yoga Foundation",
    "courseName": "50 Hour Yin Yoga Teacher Training",
    "url": "https://www.yinyogafoundation.com/",
    "type": "Yin Yoga Teacher Training",
    "certificationLevel": "50hr",
    "durationDays": 6,
    "price": {
      "amount": 300,
      "currency": "USD"
    },
    "description": "A beginner-friendly 50-hour Yin Yoga course offered in Rishikesh, India. The course covers the fundamentals of Yin Yoga practice including anatomy, meridian theory, and meditation. It is certified by Yoga Alliance USA.",
    "upcomingDates": [],
    "accommodation": "string - Residential option available",
    "meals": "string - Simple vegetarian food served",
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Yin Yoga Foundation",
    "courseName": "100 Hour Yin Yoga Teacher Training",
    "url": "https://www.yinyogafoundation.com/",
    "type": "Yin Yoga Teacher Training",
    "certificationLevel": "100hr",
    "durationDays": 12,
    "price": {
      "amount": 599,
      "currency": "USD"
    },
    "description": "A 100-hour Yin Yoga Teacher Training in Rishikesh focusing on restoring equilibrium and improving flexibility. Daily sessions concentrate on specific areas including hips, spine, legs, and shoulders. Certified by Yoga Alliance USA with a Yoga Alliance Certificate upon completion.",
    "upcomingDates": [],
    "accommodation": "string - Residential option available",
    "meals": "string - Simple vegetarian food served",
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Yin Yoga Foundation",
    "courseName": "200 Hour Yin Yoga Teacher Training",
    "url": "https://www.yinyogafoundation.com/",
    "type": "Yin Yoga Teacher Training",
    "certificationLevel": "200hr",
    "durationDays": 24,
    "price": {
      "amount": 999,
      "currency": "USD"
    },
    "description": "A comprehensive 200-hour Yin Yoga certification course in Rishikesh offering in-depth instruction in anatomy, meridian theory, mindfulness, and teaching methods. The long-term program is certified by Yoga Alliance USA and affiliated with Arogya Yoga School. Suitable for yoga teachers, therapists, and dedicated learners.",
    "upcomingDates": [],
    "accommodation": "string - Residential option available",
    "meals": "string - Simple vegetarian food served",
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Arogya Yoga School",
    "courseName": "100 Hour Yin Yoga Teacher Training in Rishikesh India",
    "url": "https://www.arogyayogaschool.com/yin-yoga-teacher-training-in-rishikesh.php",
    "type": "Yin Yoga Teacher Training",
    "certificationLevel": "100hr",
    "durationDays": 0,
    "price": {
      "amount": 500,
      "currency": "USD"
    },
    "description": "Arogya Yoga School offers a Yoga Alliance certified 100-hour Yin Yoga Teacher Training in Rishikesh, India. The program focuses on the philosophy and practice of Yin Yoga, including Taoist principles, Traditional Chinese Medicine, meridian theory, and anatomy of connective tissues. Students learn to teach Yin yoga classes, develop pranayama and meditation skills, and explore the energetic and therapeutic benefits of long-held postures.",
    "upcomingDates": [],
    "accommodation": "Single accommodation included (fee range 500–600 USD)",
    "meals": false,
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Vinyasa Yoga Ashram",
    "courseName": "50 Hours Yin Yoga Teacher Training",
    "url": "https://www.vinyasayogaashram.com/yin-yoga",
    "type": "Yin Yoga Teacher Training",
    "certificationLevel": "50hr",
    "durationDays": 7,
    "price": {
      "amount": 299,
      "currency": "USD"
    },
    "description": "A 50-hour Yin Yoga Teacher Training Course in Rishikesh covering philosophical and anatomical theory, multiple healing practices, meridian theory, and teaching methodology. Participants will gain deep understanding of Yin Yoga postures, props usage, and Traditional Chinese Medicine principles. The course culminates in a class delivery evaluation and YACEP Yoga Alliance certification.",
    "upcomingDates": [
      "2026-04-24",
      "2026-05-24",
      "2026-06-24",
      "2026-07-24",
      "2026-08-24",
      "2026-09-24",
      "2026-10-24",
      "2026-11-24",
      "2026-12-24",
      "2027-01-24",
      "2027-02-24",
      "2027-03-24"
    ],
    "accommodation": "Private room ($399 USD) or shared room ($299 USD) available; rooms include attached bathroom, 24-hour hot/cold water, free WiFi, cupboards and lockers",
    "meals": "3 vegetarian, vegan and gluten-free meals daily included",
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Vinyasa Yoga Academy",
    "courseName": "Yin Yoga Teacher Training Course In Rishikesh",
    "url": "https://vinyasayogaacademy.com/yin-yoga-training-in-rishikesh-india.php",
    "type": "Yin Yoga Teacher Training",
    "certificationLevel": "",
    "durationDays": 9,
    "price": {
      "amount": 0,
      "currency": "USD"
    },
    "description": "An intensive and carefully structured Yin Yoga Teacher Training course in Rishikesh, India, designed to provide a comprehensive understanding of practicing and teaching Yin Yoga. The course covers Yin philosophy, anatomy, sequencing, and the functional approach based on skeletal variations and uniqueness of each practitioner. Students will gain the tools and knowledge needed to deepen their practice and begin teaching Yin Yoga to others.",
    "upcomingDates": [],
    "accommodation": false,
    "meals": false,
    "rating": 5,
    "reviewCount": null
  },
  {
    "schoolName": "Vinyasa Yogashala",
    "courseName": "Online Yin Yoga Teacher Training Course",
    "url": "https://vinyasayogashala.com/online-yin-yoga-teacher-training-course.html",
    "type": "Yin Yoga Teacher Training",
    "certificationLevel": "YACEP",
    "durationDays": 10,
    "price": {
      "amount": 299,
      "currency": "USD"
    },
    "description": "An online Yin Yoga teacher training course from experienced yogis of Rishikesh, India, offering pre-recorded and live Zoom sessions. The program includes 5 contact hours and 15+ non-contact hours, covering ancient Yin Yoga techniques, deep meditation practices, and relaxation methods. Upon completion, students are eligible to register for Yoga Alliance Continuing Education Credit (YACEP).",
    "upcomingDates": [],
    "accommodation": false,
    "meals": false,
    "rating": 4.8,
    "reviewCount": 167
  },
  {
    "schoolName": "Yin Yang Yoga Academy",
    "courseName": "100 Hour Yoga Teacher Training in Rishikesh, India",
    "url": "https://yinyangyogaacademy.org/",
    "type": "Yoga Teacher Training",
    "certificationLevel": "100hr",
    "durationDays": 12,
    "price": {
      "amount": 699,
      "currency": "USD"
    },
    "description": "The 100-hour teacher training course includes subjects like meditation, pranayama, and asanas. The course helps students grasp the basic understanding of Yoga and emerge with confidence and inner harmony. It is taught in the Hatha and Ashtanga Vinyasa styles in Rishikesh, India.",
    "upcomingDates": [],
    "accommodation": "Shared Room or Private Room available",
    "meals": false,
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Yin Yang Yoga Academy",
    "courseName": "200 Hour Yoga Teacher Training in Rishikesh, India",
    "url": "https://yinyangyogaacademy.org/",
    "type": "Yoga Teacher Training",
    "certificationLevel": "200hr",
    "durationDays": 24,
    "price": {
      "amount": 1099,
      "currency": "USD"
    },
    "description": "The 200-hour yoga teacher training is ideal for beginners or intermediate practitioners who want to become yoga teachers. It is also suitable for individuals interested in a month-long yoga course to improve health, wellness, or spirituality. The course is taught in Hatha and Ashtanga Vinyasa styles in Rishikesh, India.",
    "upcomingDates": [],
    "accommodation": "Shared Room or Private Room available",
    "meals": false,
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Yin Yang Yoga Academy",
    "courseName": "300 Hour Yoga Teacher Training in Rishikesh, India",
    "url": "https://yinyangyogaacademy.org/",
    "type": "Yoga Teacher Training",
    "certificationLevel": "300hr",
    "durationDays": 28,
    "price": {
      "amount": 1299,
      "currency": "USD"
    },
    "description": "The 300-hour yoga teacher training is designed for advanced practitioners who wish to polish the art of teaching yoga. It is conducted in Rishikesh, India, and is intended for those who have already completed a 200-hour RYT with a Yoga Alliance registered school. The course is taught in Hatha and Ashtanga Vinyasa styles.",
    "upcomingDates": [],
    "accommodation": "Shared Room or Private Room available",
    "meals": false,
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Yin Yang Yoga Academy",
    "courseName": "500 Hour Yoga Teacher Training in Rishikesh, India",
    "url": "https://yinyangyogaacademy.org/",
    "type": "Yoga Teacher Training",
    "certificationLevel": "500hr",
    "durationDays": 60,
    "price": {
      "amount": 0,
      "currency": "USD"
    },
    "description": "The 500-hour yoga teacher training program at Yin Yang Yoga Academy focuses on the approach to teaching yoga. Practitioners merge the philosophy of yoga with nurturing techniques to further spread this sacred tradition. The program is conducted in Rishikesh, India.",
    "upcomingDates": [],
    "accommodation": "Shared Room or Private Room available",
    "meals": false,
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Sri Yoga Ashram",
    "courseName": "6-Day Yin Yoga Retreat (Online)",
    "url": "https://sriyogaashram.com/6-days-yin-yoga.html",
    "type": "Yin Yoga Retreat",
    "certificationLevel": "50hr",
    "durationDays": 6,
    "price": {
      "amount": 100,
      "currency": "USD"
    },
    "description": "A 6-day online Yin Yoga retreat held via Zoom, running Monday to Saturday for 1 hour per day (2 hours theory, 4 hours practice total). The course covers Yin Yoga history, principles, meridians, use of props, and all three levels from beginner to advanced. Upon completion, participants receive a Yoga Alliance USA certificate.",
    "upcomingDates": [],
    "accommodation": false,
    "meals": false,
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Sri Yoga Ashram",
    "courseName": "6-Day Yin Yoga Retreat (Offline - Shared Accommodation)",
    "url": "https://sriyogaashram.com/6-days-yin-yoga.html",
    "type": "Yin Yoga Retreat",
    "certificationLevel": "50hr",
    "durationDays": 6,
    "price": {
      "amount": 300,
      "currency": "USD"
    },
    "description": "A 6-day in-person Yin Yoga retreat at Sri Yoga Ashram in Rishikesh, India, featuring 5 classes per day including mandatory Ayurveda and Hatha Yoga sessions plus optional pranayama and meditation. Shared accommodation with attached bathroom and three Sattvic vegetarian meals per day are included. A Yoga Alliance USA certificate is awarded upon completion.",
    "upcomingDates": [],
    "accommodation": "Twin shared room with attached bathroom, hot water, and power backup included",
    "meals": "Three Sattvic vegetarian meals per day plus two times tea included",
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Sri Yoga Ashram",
    "courseName": "6-Day Yin Yoga Retreat (Offline - Private Accommodation)",
    "url": "https://sriyogaashram.com/6-days-yin-yoga.html",
    "type": "Yin Yoga Retreat",
    "certificationLevel": "50hr",
    "durationDays": 6,
    "price": {
      "amount": 350,
      "currency": "USD"
    },
    "description": "A 6-day in-person Yin Yoga retreat at Sri Yoga Ashram in Rishikesh, India, featuring 5 classes per day including mandatory Ayurveda and Hatha Yoga sessions plus optional pranayama and meditation. Private accommodation with attached bathroom and three Sattvic vegetarian meals per day are included. A Yoga Alliance USA certificate is awarded upon completion.",
    "upcomingDates": [],
    "accommodation": "Private room with attached bathroom, hot water, and power backup included",
    "meals": "Three Sattvic vegetarian meals per day plus two times tea included",
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Rishikesh Yoga Association",
    "courseName": "50 Hour Yin Yoga Teacher Training Course in Rishikesh",
    "url": "https://www.rishikeshyogaassociation.com/85-hour-yin-yoga-teacher-training-course-in-rishikesh.php",
    "type": "Yin Yoga Teacher Training",
    "certificationLevel": "50hr",
    "durationDays": 7,
    "price": {
      "amount": 300,
      "currency": "USD"
    },
    "description": "A 50-hour Yin Yoga Teacher Training Course in Rishikesh, India, affiliated with Yoga Alliance USA. The program provides an in-depth understanding of Yin Yoga covering pranayama, asanas, anatomy, philosophy, meditation, and teaching methodology. Participants will be trained by renowned yoga instructors to become licensed Yin Yoga teachers.",
    "upcomingDates": [
      "2026-03-24",
      "2026-04-24",
      "2026-05-24",
      "2026-06-24",
      "2026-07-24",
      "2026-08-24",
      "2026-09-24",
      "2026-10-24"
    ],
    "accommodation": "6 nights twin shared accommodation with hot water, attached bath and toilet",
    "meals": "3 times daily nutritious vegetarian meals and teas",
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Peace Yoga Retreat",
    "courseName": "3 Days Yin Yoga Retreat",
    "url": "https://www.peaceyogaretreat.com/yin-yoga-retreats/",
    "type": "Yin Yoga Retreat",
    "certificationLevel": "",
    "durationDays": 3,
    "price": {
      "amount": 0,
      "currency": "INR"
    },
    "description": "A 3-day Yin Yoga retreat offering 2 Yin Yoga classes per day along with Meditation and Pranayama. Suitable for beginners and advanced practitioners alike. Available in Goa (October to May) and Rishikesh (year-round).",
    "upcomingDates": [],
    "accommodation": true,
    "meals": true,
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Peace Yoga Retreat",
    "courseName": "7 Days Yin Yoga Retreat",
    "url": "https://www.peaceyogaretreat.com/yin-yoga-retreats/",
    "type": "Yin Yoga Retreat",
    "certificationLevel": "",
    "durationDays": 7,
    "price": {
      "amount": 0,
      "currency": "INR"
    },
    "description": "A 7-day Yin Yoga retreat offering 2 Yin Yoga classes per day along with Meditation and Pranayama. Suitable for beginners and advanced practitioners alike. Available in Goa (October to May) and Rishikesh (year-round).",
    "upcomingDates": [],
    "accommodation": true,
    "meals": true,
    "rating": null,
    "reviewCount": null
  },
  {
    "schoolName": "Peace Yoga Retreat",
    "courseName": "14 Days Yin Yoga Retreat",
    "url": "https://www.peaceyogaretreat.com/yin-yoga-retreats/",
    "type": "Yin Yoga Retreat",
    "certificationLevel": "",
    "durationDays": 14,
    "price": {
      "amount": 0,
      "currency": "INR"
    },
    "description": "A 14-day Yin Yoga retreat offering 2 Yin Yoga classes per day along with Meditation and Pranayama. Suitable for beginners and advanced practitioners alike. Available in Goa (October to May) and Rishikesh (year-round).",
    "upcomingDates": [],
    "accommodation": true,
    "meals": true,
    "rating": null,
    "reviewCount": null
  }
]
